development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: AionAgileManager_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: AionAgileManager_test

production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] %>
  channel_prefix: AionAgileManager_production
